logging:
  level: INFO
  loggers:
    com: DEBUG

server:
  adminContextPath: /
  applicationContextPath: /
  applicationConnectors:
    - type: http
      port: 9091
  adminConnectors:
    - type: http
      port: 8091
